POLICY_PROJECT_ID = "GCP Project ID" 
POLICY_REGION     = "One of the GCP Regions, like `us-central1`" 
CLOUD_BUILD_SA    = "Cloud Build Service Account, like project-number@cloudbuild.gserviceaccount.com" 
BA_KEYRING        = "Key Ring Name"
BA_KEY            = "Key Name"
BA_NOTE_ID        = "Note ID"
BA_NOTE_NAME      = "Note Name"
BA_VULNERABILITY_ATTESTOR = "Attestor Name"