steps:
# Run a shell script; and
# set env variables for its execution
#- name: 'ubuntu'
#  args: ['bash', './scanner.sh']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['./scanner.sh']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'CLOUD_RUN_APP_NAME=hello'
  - 'BA_VULNERABILITY_ATTESTOR=ba-vulnerability-attestor2'
  - 'BA_KEY=ba-vulnerability-signer2'
  - 'BA_KEYRING=ba-vulnerability-kr2'
